/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session bootstrap: CSRF token and service identity, released only to
         *     accepted loopback hosts, never cached.
         */
        get: operations["bootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists jobs with stable cursor pagination, newest first. */
        get: operations["list_jobs"];
        put?: never;
        /**
         * Creates a job: validate, persist durable intent, then enqueue. The
         *     response returns the current durable job view.
         */
        post: operations["create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One job with its durable attempt history. */
        get: operations["get_job"];
        put?: never;
        post?: never;
        /** Removes a terminal job's durable history. Never touches files. */
        delete: operations["delete_job"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancels the job with an explicit artifact policy. */
        post: operations["cancel_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pauses the job when the caller's version is current. */
        post: operations["pause_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resumes the job when the caller's version is current. */
        post: operations["resume_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retries a terminal job under the same history. */
        post: operations["retry_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveals a completed artifact's parent directory via the desktop
         *     integration. Only completed jobs with a recorded resolved destination
         *     qualify.
         */
        post: operations["reveal_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists configured roots with canonical paths. */
        get: operations["list_roots"];
        put?: never;
        /**
         * Adds an existing directory as a configured root. This is the explicit
         *     authorization step, so an absolute path is expected here.
         */
        post: operations["create_root"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One configured root. */
        get: operations["get_root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Updates label, enabled state, or default flag of a root. */
        patch: operations["patch_root"];
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the typed global settings. */
        get: operations["get_settings"];
        /**
         * Validates and persists settings, then applies the transfer limits to
         *     the supervisor. Lowering active concurrency never cancels running work;
         *     it only prevents the next launch until the count falls below the limit.
         */
        put: operations["put_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Machine-stable error envelope: `code` identifies the failure class,
         *     `message` is a safe user-facing summary, and optional fields carry
         *     structured context. Secrets, URL query values, and credentials never
         *     appear in `message` or `detail`.
         */
        ApiErrorEnvelope: {
            code: string;
            current_job?: null | components["schemas"]["JobViewDto"];
            detail?: string | null;
            field_errors?: {
                [key: string]: string;
            } | null;
            message: string;
            retryable: boolean;
        };
        /** @description Typed global settings as stored. */
        AppSettingsDto: {
            /** Format: int32 */
            active_concurrency: number;
            /** Format: uuid */
            default_root_id?: string | null;
            notifications_enabled: boolean;
            /** Format: int64 */
            rate_limit_bytes_per_second?: number | null;
            /** @description One of `manual`, `service`. */
            startup_mode: string;
        };
        /**
         * @description What cancellation should do with partial artifacts.
         * @enum {string}
         */
        ArtifactPolicyDto: "preserve_partial" | "delete_partial" | "keep_file_discard_checkpoint";
        /**
         * @description One attempt in a job's durable history. Absolute paths are never
         *     exposed here; the job view carries relative display destinations.
         */
        AttemptDto: {
            /** Format: int64 */
            finished_at?: number | null;
            /** Format: uuid */
            id: string;
            outcome?: null | components["schemas"]["AttemptOutcomeDto"];
            /** @description One of `initial`, `retry`, `recovery`. */
            reason: string;
            /** Format: int64 */
            started_at: number;
        };
        /** @description Final byte counts and wall time of an attempt. */
        AttemptMetricsDto: {
            /** Format: int64 */
            bytes_received: number;
            /** Format: int64 */
            duration_ms: number;
            /** Format: int64 */
            network_bytes: number;
        };
        /** @description Terminal result of one attempt, display-safe. */
        AttemptOutcomeDto: {
            code?: string | null;
            detail?: string | null;
            /** @description One of `completed`, `failed`, `cancelled`, `interrupted`. */
            kind: string;
            metrics?: null | components["schemas"]["AttemptMetricsDto"];
        };
        /** @description Session/bootstrap data: the CSRF token plus service identity. */
        BootstrapDto: {
            build: string;
            csrf_token: string;
            origin: string;
            stream_epoch: string;
            suggested_download_root?: string | null;
        };
        /** @description Cancel preconditions plus the explicit artifact choice. */
        CancelJobCommand: {
            artifact_policy: components["schemas"]["ArtifactPolicyDto"];
            /** Format: int64 */
            expected_control_version: number;
        };
        /**
         * @description What happens when the destination already exists.
         * @enum {string}
         */
        ConflictPolicyDto: "fail_if_exists" | "overwrite" | "rename" | "resume";
        /**
         * @description Request body for creating a job. Ordinary creation never carries
         *     absolute destinations: an opaque root ID plus relative paths only.
         */
        CreateJobRequest: {
            conflict_policy?: null | components["schemas"]["ConflictPolicyDto"];
            filename_override?: string | null;
            relative_directory?: string | null;
            /** Format: uuid */
            root_id: string;
            source_url: string;
        };
        /** @description Request to add an existing directory as a configured root. */
        CreateRootRequest: {
            absolute_path: string;
            label: string;
            make_default?: boolean;
        };
        /**
         * @description User-facing desired state.
         * @enum {string}
         */
        DesiredStateDto: "Running" | "Paused" | "Cancelled";
        /**
         * @description Durable lifecycle status as the UI presents it.
         * @enum {string}
         */
        DurableJobStatusDto: "Queued" | "Recovering" | "Active" | "Paused" | "Completed" | "Failed" | "Cancelled";
        /** @description Display-safe telemetry snapshot. */
        EngineSnapshotViewDto: {
            /** Format: int64 */
            bytes_received: number;
            /** Format: int64 */
            elapsed_ms: number;
            /** Format: int64 */
            network_bytes: number;
            /** Format: int64 */
            retries: number;
            /** Format: int64 */
            reused_bytes: number;
            state_label: string;
        };
        /**
         * @description One SSE stream event. `job` carries the complete display-safe view for
         *     `job.snapshot`; `hello` carries the stream epoch and build identity.
         */
        EventEnvelopeDto: {
            build?: string | null;
            job?: null | components["schemas"]["JobViewDto"];
            /**
             * @description One of `hello`, `job.snapshot`, `job.removed`, `settings.changed`,
             *     `service.degraded`.
             */
            kind: string;
            /** @description Process stream epoch: changes across service restarts. */
            stream_epoch: string;
        };
        /** @description One job with its durable attempt history. */
        JobDetailDto: {
            attempts: components["schemas"]["AttemptDto"][];
            job: components["schemas"]["JobViewDto"];
        };
        /** @description One page of the jobs collection. */
        JobPageDto: {
            jobs: components["schemas"]["JobViewDto"][];
            next_cursor?: string | null;
        };
        /**
         * @description Display-safe job view. Source URLs are redacted; filesystem paths are
         *     reduced to relative display form.
         */
        JobViewDto: {
            /** Format: uuid */
            attempt_id?: string | null;
            /** Format: int64 */
            control_version: number;
            /** Format: int64 */
            created_at: number;
            desired_state: components["schemas"]["DesiredStateDto"];
            /** @description Final display destination relative to the root, once completed. */
            destination_display?: string | null;
            filename_override?: string | null;
            /** Format: uuid */
            id: string;
            relative_directory?: string | null;
            /** Format: uuid */
            root_id: string;
            /** @description Root label; ordinary job views never carry absolute paths. */
            root_label: string;
            /** Format: int64 */
            sample_seq: number;
            snapshot?: null | components["schemas"]["EngineSnapshotViewDto"];
            source_display: string;
            status: components["schemas"]["DurableJobStatusDto"];
            /** Format: int64 */
            updated_at: number;
        };
        /** @description Partial root update. */
        PatchRootRequest: {
            enabled?: boolean | null;
            label?: string | null;
            make_default?: boolean | null;
        };
        /** @description Lifecycle command preconditions: the caller's last observed version. */
        PauseJobCommand: {
            /** Format: int64 */
            expected_control_version: number;
        };
        /** @description Resume preconditions. */
        ResumeJobCommand: {
            /** Format: int64 */
            expected_control_version: number;
        };
        /** @description Retry preconditions. */
        RetryJobCommand: {
            /** Format: int64 */
            expected_control_version: number;
        };
        /**
         * @description A configured root as the administration surface presents it. This is
         *     the only DTO family that may carry absolute filesystem paths.
         */
        RootDto: {
            canonical_path: string;
            /** Format: int64 */
            created_at: number;
            enabled: boolean;
            /** Format: uuid */
            id: string;
            is_default: boolean;
            label: string;
            /** Format: int64 */
            updated_at: number;
        };
        /** @description Root identity without filesystem paths, safe for bootstrap. */
        RootSummaryDto: {
            enabled: boolean;
            /** Format: uuid */
            id: string;
            is_default: boolean;
            label: string;
        };
        /** @description Full settings update (PUT semantics: every field is required). */
        UpdateSettingsRequest: {
            /** Format: int32 */
            active_concurrency: number;
            /** Format: uuid */
            default_root_id?: string | null;
            notifications_enabled: boolean;
            /** Format: int64 */
            rate_limit_bytes_per_second?: number | null;
            startup_mode: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session bootstrap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapDto"];
                };
            };
            /** @description Unexpected host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                /** @description Opaque continuation cursor */
                cursor?: string;
                /** @description Page size (1-200) */
                limit?: number;
                /** @description Durable status filter */
                status?: string;
                /** @description Source URL substring filter */
                source?: string;
                /** @description Created-at lower bound (epoch ms) */
                from?: number;
                /** @description Created-at upper bound (epoch ms) */
                to?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPageDto"];
                };
            };
        };
    };
    create_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Job created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobViewDto"];
                };
            };
            /** @description Validation failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Service degraded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailDto"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    delete_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job is not terminal */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    cancel_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelJobCommand"];
            };
        };
        responses: {
            /** @description Cancel accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobViewDto"];
                };
            };
            /** @description Stale version or illegal transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    pause_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PauseJobCommand"];
            };
        };
        responses: {
            /** @description Paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobViewDto"];
                };
            };
            /** @description Stale version or illegal transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    resume_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeJobCommand"];
            };
        };
        responses: {
            /** @description Resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobViewDto"];
                };
            };
            /** @description Stale version or illegal transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    retry_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryJobCommand"];
            };
        };
        responses: {
            /** @description Retry accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobViewDto"];
                };
            };
            /** @description Stale version or illegal transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    reveal_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revealed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job is not completable for reveal */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    list_roots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Root list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootDto"][];
                };
            };
        };
    };
    create_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRootRequest"];
            };
        };
        responses: {
            /** @description Root added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootDto"];
                };
            };
            /** @description Path is not an existing directory */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    get_root: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Root */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootDto"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    patch_root: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRootRequest"];
            };
        };
        responses: {
            /** @description Root updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootDto"];
                };
            };
            /** @description Root in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid update */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsDto"];
                };
            };
        };
    };
    put_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Settings saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsDto"];
                };
            };
            /** @description Invalid values */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
}
