//! Checkpoint persistence: trait + atomic sidecar store (§15.3, §34, D3).

use std::io::Write;
use std::path::{Path, PathBuf};

use crate::resume::checkpoint::{Checkpoint, CheckpointError};

/// Durability level for checkpoint persistence (§15.4, D4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DurabilityMode {
    /// Checkpoint represents page-cache-acknowledged writes (§15.4
    /// performance mode). After power loss some recorded bytes may need
    /// redownload.
    #[default]
    Performance,
    /// Data flushed before completed intervals are recorded; the
    /// checkpoint fsyncs before rename.
    Durable,
}

/// Storage abstraction (§34): pluggable (sidecar, SQLite, app state).
pub trait CheckpointStore: Send + Sync {
    /// Load a checkpoint; `Ok(None)` when absent.
    ///
    /// # Errors
    /// [`CheckpointError`] when present but unreadable/corrupt.
    fn load(&self, job_identity: &str) -> Result<Option<Checkpoint>, CheckpointError>;

    /// Atomically replace the checkpoint (§15.3: write-temp → fsync →
    /// rename → optional dir fsync).
    ///
    /// # Errors
    /// I/O failures map to [`CheckpointError`].
    fn save_atomic(&self, checkpoint: &Checkpoint) -> Result<(), CheckpointError>;

    /// Remove persisted state (§14.6 step 5).
    ///
    /// # Errors
    /// I/O failure; missing file is not an error.
    fn delete(&self, job_identity: &str) -> Result<(), CheckpointError>;
}

/// Sidecar-file store (§34 default): `<dir>/<job_identity>.kdown`.
#[derive(Debug, Clone)]
pub struct FileCheckpointStore {
    dir: PathBuf,
    durability: DurabilityMode,
}

impl FileCheckpointStore {
    /// Store checkpoints in `dir` with the given durability mode.
    ///
    /// # Errors
    /// Returns an error when `dir` cannot be created.
    pub fn new(dir: &Path, durability: DurabilityMode) -> Result<Self, CheckpointError> {
        std::fs::create_dir_all(dir)
            .map_err(|e| CheckpointError::Corrupt(format!("mkdir {}: {e}", dir.display())))?;
        Ok(Self {
            dir: dir.to_path_buf(),
            durability,
        })
    }

    fn path_for(&self, job_identity: &str) -> PathBuf {
        // Identity is a filesystem-safe token generated by the engine.
        self.dir.join(format!("{job_identity}.kdown"))
    }
}

impl CheckpointStore for FileCheckpointStore {
    fn load(&self, job_identity: &str) -> Result<Option<Checkpoint>, CheckpointError> {
        let path = self.path_for(job_identity);
        match std::fs::read(&path) {
            Ok(bytes) => {
                let json = String::from_utf8(bytes)
                    .map_err(|e| CheckpointError::Corrupt(format!("checkpoint not utf-8: {e}")))?;
                Checkpoint::from_json(&json).map(Some)
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(CheckpointError::Corrupt(format!(
                "read {}: {e}",
                path.display()
            ))),
        }
    }

    fn save_atomic(&self, checkpoint: &Checkpoint) -> Result<(), CheckpointError> {
        let json = checkpoint.to_json()?;
        let path = self.path_for(&checkpoint.job_id);
        let tmp_path = self
            .dir
            .join(format!("{}.{}.tmp", checkpoint.job_id, std::process::id()));
        {
            let mut f = std::fs::File::create(&tmp_path).map_err(|e| {
                CheckpointError::Corrupt(format!("create {}: {e}", tmp_path.display()))
            })?;
            f.write_all(json.as_bytes())
                .map_err(|e| CheckpointError::Corrupt(format!("write: {e}")))?;
            f.flush()
                .map_err(|e| CheckpointError::Corrupt(format!("flush: {e}")))?;
            if self.durability == DurabilityMode::Durable {
                f.sync_all()
                    .map_err(|e| CheckpointError::Corrupt(format!("fsync checkpoint: {e}")))?;
            }
        }
        std::fs::rename(&tmp_path, &path).map_err(|e| {
            CheckpointError::Corrupt(format!(
                "rename {} -> {}: {e}",
                tmp_path.display(),
                path.display()
            ))
        })?;
        if self.durability == DurabilityMode::Durable {
            // Directory fsync so the rename itself survives power loss
            // (§15.3 step 4).
            if let Some(parent) = path.parent() {
                if let Ok(dir_file) = std::fs::File::open(parent) {
                    let _ = dir_file.sync_all();
                }
            }
        }
        Ok(())
    }

    fn delete(&self, job_identity: &str) -> Result<(), CheckpointError> {
        let path = self.path_for(job_identity);
        match std::fs::remove_file(&path) {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(CheckpointError::Corrupt(format!("delete: {e}"))),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::http::validators::ResourceValidators;

    fn sample(job: &str) -> Checkpoint {
        let mut cp = Checkpoint::new(job, "https://example/f", "tmp-1");
        cp.validators = ResourceValidators {
            etag: Some("\"v\"".into()),
            etag_is_weak: false,
            last_modified: None,
            total_size: Some(100),
        };
        cp.record_completed(0, 49);
        cp
    }

    #[test]
    fn save_load_roundtrip() {
        let dir = tempfile::tempdir().expect("tmp");
        let store =
            FileCheckpointStore::new(dir.path(), DurabilityMode::Performance).expect("store");
        store.save_atomic(&sample("job-a")).expect("save");
        let loaded = store.load("job-a").expect("load");
        assert!(loaded.is_some());
        assert_eq!(loaded.expect("some").completed_ranges, vec![(0, 49)]);
    }

    #[test]
    fn missing_checkpoint_is_none_not_error() {
        let dir = tempfile::tempdir().expect("tmp");
        let store =
            FileCheckpointStore::new(dir.path(), DurabilityMode::Performance).expect("store");
        assert!(store.load("absent").expect("none").is_none());
    }

    #[test]
    fn atomic_replace_never_leaves_unreadable() {
        // Simulate the write-temp/rename cycle: an interrupted save leaves
        // either the old checkpoint or the new one, never garbage (§15.3).
        let dir = tempfile::tempdir().expect("tmp");
        let store =
            FileCheckpointStore::new(dir.path(), DurabilityMode::Performance).expect("store");
        store.save_atomic(&sample("job-b")).expect("save 1");
        let mut cp = sample("job-b");
        cp.record_completed(50, 99);
        store.save_atomic(&cp).expect("save 2");
        let loaded = store.load("job-b").expect("load");
        assert_eq!(loaded.expect("some").completed_ranges, vec![(0, 99)]);
        // No .tmp residue after a successful save.
        let leftovers: Vec<_> = std::fs::read_dir(dir.path())
            .expect("dir")
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().ends_with(".tmp"))
            .collect();
        assert!(leftovers.is_empty(), "tmp files must be renamed away");
    }

    #[test]
    fn delete_removes_and_missing_ok() {
        let dir = tempfile::tempdir().expect("tmp");
        let store = FileCheckpointStore::new(dir.path(), DurabilityMode::Durable).expect("store");
        store.save_atomic(&sample("job-c")).expect("save");
        store.delete("job-b").expect("missing delete is ok");
        store.delete("job-a").expect("delete");
        assert!(store.load("job-a").expect("gone").is_none());
    }
}
